apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db2-pvc
  namespace: ecom
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db2
  namespace: ecom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db2
  template:
    metadata:
      labels:
        app: postgres-db2
    spec:
      containers:
        - name: pg
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB2_NAME
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB2_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: DB2_PASS
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: db2-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db2
  namespace: ecom
spec:
  selector:
    app: postgres-db2
  ports:
    - port: 5432
      targetPort: 5432
